#!/bin/bash

VOLUME=$(osascript -e 'set ovol to output volume of (get volume settings)')
ICON="🔈"

if [ "$VOLUME" = "missing value" ]; then
	VOLUME=0
	ICON="<i class='fas fa-volume-off'></i>"
fi

if (( $VOLUME > 66 )); then
	ICON="<i class='fas fa-volume-up'></i>"
elif (( $VOLUME > 33 )); then
	ICON="<i class='fas fa-volume-down'></i>"
elif (( $VOLUME > 0 )); then
	ICON="<i class='fas fa-volume-off'></i>"
else
	ICON="<i class='fas fa-volume-mute'></i>"
fi

echo $ICON
echo $VOLUME
