#!/bin/bash


curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

pip3 install --user pynvim
pip install --user pynvim
npm i -g neovim
gem install neovim
