#!/bin/bash

BREW_INSTALL_THESE="zsh zsh-completions neovim golang neofetch ripgrep"

if hash brew 2>/dev/null; then
	brew install $BREW_INSTALL_THESE
else
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brew install $BREW_INSTALL_THESE
fi

chsh -s /bin/zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
