#!/bin/bash

sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt update

INSTALL_THESE="curl zsh neovim golang python3 python3-pip python2 ruby neofetch ripgrep fzf"

sudo apt install $INSTALL_THESE

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
nvm install 10

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
