#!/bin/bash

INSTALL_THESE="rofi termite zsh neovim go python python2 ruby neofetch ripgrep fzf"

if hash yay 2>/dev/null; then
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si
	cd ..
	rm -rf yay
fi

# Setup Bonclay
if hash bonclay 2>/dev/null; then
	bonclay sync linux.yaml
else
	sh -c "$(curl -sL git.io/getbonclay)"
	bonclay sync linux.yaml
fi

sudo pacman -Sy $INSTALL_THESE

# Setup NVM
if hash nvm 2>/dev/null; then
	nvm install 10
else
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
	source ~/.zshrc
	nvm install 10
fi

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

