#!/bin/bash

INSTALL_THESE="curl zsh neovim golang python python2 ruby neofetch ripgrep fzf"

sudo apt install $INSTALL_THESE

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
nvm install 10

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
