#!/bin/bash

INSTALL_THESE="alacritty zsh neovim go python python2 ruby neofetch ripgrep fzf noto-fonts-emoji powerline-fonts"
AUR_THESE="nvm ttf-fira-code ttf-fira-sans ttf-fira-mono ttf-fira-go"

if !hash yay 2>/dev/null; then
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si
	cd ..
	rm -rf yay
fi

sudo pacman -Sy $INSTALL_THESE
yay -S $AUR_THESE

nvm install 10

sudo cp -r fonts/Dank /usr/share/fonts
sudo cp -r fonts/icomoon /usr/share/fonts

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
