#!/bin/bash
sudo dnf copr enable atim/starship
sudo dnf copr enable dejan/lazygit
INSTALL_THESE="curl zsh neovim golang python ruby fastfetch ripgrep fzf starship nodejs npm kitty lazygit direnv"

sudo dnf install "$INSTALL_THESE" -y

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
