#!/bin/bash

INSTALL_THESE="rofi dunst nitrogen termite zsh zsh-completions neovim go python python2 ruby neofetch ripgrep"
AUR_INSTALL_THESE="compton-tryone-git"

if hash yay 2>/dev/null; then
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si
	cd ..
	rm -rf yay
fi

# Setup Bonclay
if hash bonclay 2>/dev/null; then
	bonclay sync linux.yaml
else
	sh -c "$(curl -sL git.io/getbonclay)"
	bonclay sync linux.yaml
fi

sudo pacman -Sy $INSTALL_THESE
yay -S $AUR_INSTALL_THESE

# Setup NVM
if hash nvm 2>/dev/null; then
	nvm install 10
else
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
	source ~/.zshrc
	nvm install 10
fi

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
