#!/bin/sh

xsetroot -cursor_name left_ptr
$HOME/dotfiles/polybar/launch.sh
nitrogen --restore &
picom &
dunst &
sxhkd &
screenrotator &
pulseeffects --gapplication-service &

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
monitors=0
for m in $(xrandr --listactivemonitors | grep "DP" | cut -d " " -f6); do
	((monitors++))
done

echo $monitors
if (( "$monitors" > "1" )); then
	bspc monitor DP-2 -d tty web mail file 5
	bspc monitor eDP-1 -d chat 7 8 dev git
else
	bspc monitor eDP-1 -d tty web mail file 5 chat 7 8 dev git
fi

# If you want a multi-monitor display or something else, I leave that to you to
# arrange. I have this sensible default for most people's use cases.


bspc config border_width 0
bspc config window_gap 16
bspc config top_padding 32	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

dropdownname="dropdown"
bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
bspc rule -a St:$dropdownname hidden=on
bspc rule -a St:$dropdownname sticky=on
bspc rule -a St:$dropdownname state=floating
bspc config external_rules_command "$(which floaters)"

bspc rule -a pauvcontrol state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating

bspc rule -a Termite desktop=^1
bspc rule -a firefox desktop=^2
bspc rule -a electron-mail desktop=^3
bspc rule -a pcmanfm desktop=^4
bspc rule -a Slack desktop=^6
bspc rule -a GitKraken desktop=^10
