#!/bin/sh

function run_once() {
	echo $1 $2
	pgrep -x $1 >/dev/null && echo "running" || ${1,,} $2 &
}

xsetroot -cursor_name left_ptr
$HOME/dotfiles/polybar/launch.sh
nitrogen --restore &
run_once picom
run_once dunst
run_once sxhkd
# run_once clight
run_once screenrotator
run_once pulseeffects --gapplication-service
xset r rate 300 50 &
amixer -q -c 0 sset Master 100% &

# If refreshing brspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

$HOME/dotfiles/bspwm/monitors.sh

bspc config border_width 0
bspc config window_gap 16
bspc config top_padding 32	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

# bscp config remove_disabled_monitors true
# bspc config remove_unplugged_monitor true
# bspc config merge_overlapping_monitors true
# bspc config pointer_follows_monitor true

bspc rule -a pauvcontrol state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a firefox:Toolkit state=floating

bspc rule -a kitty desktop=^1
bspc rule -a firefox desktop=^2
bspc rule -a Thunderbird desktop=^3
bspc rule -a Thunar desktop=^4
bspc rule -a discord desktop=^5
bspc rule -a MellowPlayer3 desktop=^10
bspc rule -a Slack desktop=^6
bspc rule -a TelegramDesktop desktop=^6

# start programs
run_once kitty
run_once firefox
run_once thunderbird
run_once thunar
run_once Discord
